from tkinter import *
from random import *

def enterB1(event):
    b1.configure(text='Alas the ghost says.')

def leaveB1(event):
    b1.configure(text='I love her, but she does not love me anymore.')

master = Tk()

b1 = Button(master)
b1.grid(row=10, column=0, sticky='W',pady=4)
b1.bind('<Enter>', enterB1)
b1.bind('<Leave>', leaveB1)

'''
b2 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b2.grid(row=9, column=0, sticky='W', pady=4)
    b3 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b3.grid(row=8, column=0, sticky='W', pady=4)
    b4 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b4.grid(row=7, column=0, sticky='W', pady=4)
    b5 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b5.grid(row=6, column=0, sticky='W', pady=4)
    b6 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b6.grid(row=5, column=0, sticky='W', pady=4)
    b7 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b7.grid(row=4, column=0, sticky='W', pady=4)
    b8 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b8.grid(row=3, column=0, sticky='W', pady=4)
    b9 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b9.grid(row=2, column=0, sticky='W', pady=4)
    b10 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b10.grid(row=1, column=0, sticky='W', pady=4)
    b11 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b11.grid(row=0, column=0, sticky='W', pady=4)
    b12 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b12.grid(row=10, column=1, sticky='W', pady=4)
    b13 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b13.grid(row=9, column=1, sticky='W', pady=4)
    b14 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b14.grid(row=8, column=1, sticky='W', pady=4)
    b15 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b15.grid(row=7, column=1, sticky='W', pady=4)
    b16 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b16.grid(row=6, column=1, sticky='W', pady=4)
    b17 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b17.grid(row=5, column=1, sticky='W', pady=4)
    b18 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b18.grid(row=4, column=1, sticky='W', pady=4)
    b19 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b19.grid(row=3, column=1, sticky='W', pady=4)
    b20 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b20.grid(row=2, column=1, sticky='W', pady=4)
    b21 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b21.grid(row=1, column=1, sticky='W', pady=4)
    b22 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b22.grid(row=0, column=1, sticky='W', pady=4)
    b23 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b23.grid(row=10, column=2, sticky='W', pady=4)
    b24 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b24.grid(row=9, column=2, sticky='W', pady=4)
    b25 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b25.grid(row=8, column=2, sticky='W', pady=4)
    b26 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b26.grid(row=7, column=2, sticky='W', pady=4)
    b27 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b27.grid(row=6, column=2, sticky='W', pady=4)
    b28 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b28.grid(row=5, column=2, sticky='W', pady=4)
    b29 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b29.grid(row=4, column=2, sticky='W', pady=4)
    b30 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b30.grid(row=3, column=2, sticky='W', pady=4)
    b31 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b31.grid(row=2, column=2, sticky='W', pady=4)
    b32 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b32.grid(row=1, column=2, sticky='W', pady=4)
    b33 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b33.grid(row=0, column=2, sticky='W', pady=4)
    b35 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b35.grid(row=10, column=3, sticky='W', pady=4)
    b36 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b36.grid(row=9, column=3, sticky='W', pady=4)
    b37 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b37.grid(row=8, column=3, sticky='W', pady=4)
    b38 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b38.grid(row=7, column=3, sticky='W', pady=4)
    b39 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b39.grid(row=6, column=3, sticky='W', pady=4)
    b40 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b40.grid(row=5, column=3, sticky='W', pady=4)
    b41 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b41.grid(row=4, column=3, sticky='W', pady=4)
    b42 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b42.grid(row=3, column=3, sticky='W', pady=4)
    b43 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b43.grid(row=2, column=3, sticky='W', pady=4)
    b44 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b44.grid(row=1, column=3, sticky='W', pady=4)
    b45 = Button(master, text='The tower of words goes further.', command=false_path_entry)
    b45.grid(row=0, column=3, sticky='W', pady=4)

'''

mainloop()